---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: $GOQOURUM_NODE
  labels:
    app: $GOQOURUM_NODE
  namespace: quorum
spec:
  replicas: 1
  selector:
    matchLabels:
      app: $GOQOURUM_NODE
  serviceName: $GOQOURUM_NODE
  volumeClaimTemplates:
    - metadata:
        name: data
      spec:
        storageClassName: nfs-client
        accessModes:
          - ReadWriteMany
        resources:
          requests:
            storage: "20Gi"
  template:
    metadata:
      labels:
        app: $GOQOURUM_NODE
        tier: backend
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "9545"
        prometheus.io/path: "/debug/metrics/prometheus"
    spec:
      serviceAccountName: $GOQOURUM_NODE-sa
      containers:
        - name: $GOQOURUM_NODE
          image: quorumengineering/quorum:latest
          imagePullPolicy: IfNotPresent
          resources:
            requests:
              cpu: 100m
              memory: 1024Mi
            limits:
              cpu: 500m
              memory: 2048Mi
          env:
            - name: POD_IP
              valueFrom:
                fieldRef:
                  fieldPath: status.podIP
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: QUORUM_NETWORK_ID
              value: "1337"
            - name: QUORUM_CONSENSUS
              value: istanbul
            - name: PRIVATE_CONFIG
              value: ignore
          volumeMounts:
            - name: keys
              mountPath: /config/keys/
              readOnly: true
            - name: static-nodes-file
              mountPath: /config/static-nodes
              readOnly: true
            - name: permissions-nodes-config
              mountPath: /config/permissions-nodes/
              readOnly: true
            - name: genesis-file
              mountPath: /config/quorum/
              readOnly: true
            - name: data
              mountPath: /data
          ports:
            - containerPort: 8545
              name: json-rpc
              protocol: TCP
            - containerPort: 8546
              name: ws
              protocol: TCP
            - containerPort: 8547
              name: graphql
              protocol: TCP
            - containerPort: 30303
              name: rlpx
              protocol: TCP
            - containerPort: 30303
              name: discovery
              protocol: UDP
            - containerPort: 9545
              name: metrics
              protocol: TCP
          command:
            - /bin/sh
            - -c
          args:
            - |
              exec 
              cp /config/static-nodes/static-nodes.json /data/
              cp /config/permissions-nodes/*.json /data/
              cp /config/quorum/genesis.json /data/
              geth --datadir=/data init /config/quorum/genesis.json
              cp /config/keys/accountkey /data/keystore/key
              cp /config/keys/nodekey /data/geth/nodekey

              geth \
              --datadir /data \
              --nodiscover \
              --nat=any \
              --permissioned \
              --emitcheckpoints \
              --verbosity 5 \
              --istanbul.blockperiod 1 --mine --miner.threads 1 \
              --syncmode full \
              --networkid ${QUORUM_NETWORK_ID} \
              --http --http.addr 0.0.0.0 --http.port 8545 --http.corsdomain "*" --http.vhosts "*" --http.api admin,db,eth,debug,miner,net,shh,txpool,personal,web3,quorum,istanbul \
              --ws --ws.addr 0.0.0.0 --ws.port 8546 --ws.origins "*" --ws.api admin,db,eth,debug,miner,net,shh,txpool,personal,web3,quorum,istanbul \
              --port 30303 \
              --unlock 0 \
              --allow-insecure-unlock \
              --metrics --pprof --pprof.addr 0.0.0.0 --pprof.port 9545 \
              --password /config/keys/password.txt
          livenessProbe:
            httpGet:
              path: /
              port: 8545
            initialDelaySeconds: 120
            periodSeconds: 30
      volumes:
        - name: keys
          secret:
            secretName: $GOQOURUM_NODE-keys
        - name: genesis-file
          configMap:
            name: goquorum-genesis
            items:
              - key: genesis.json
                path: genesis.json
        - name: static-nodes-file
          configMap:
            name: goquorum-peers
            items:
              - key: static-nodes.json
                path: static-nodes.json
        - name: permissions-nodes-config
          configMap:
            name: permissioned-nodes.json
