---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "goquorum-node.fullname" . }}-storage
spec:
  storageClassName: nfs-storage
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: "{{ .Values.storage.sizeLimit }}"