---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: $METADATA_NAME-sa
  namespace: quorum

---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: $METADATA_NAME-role
  namespace: quorum
rules:
  - apiGroups: [""]
    resources: ["secrets"]
    verbs: ["get"]
  - apiGroups: [""]
    resources: ["services"]
    verbs: ["get", "list"]

---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: $METADATA_NAME-rb
  namespace: quorum
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: $METADATA_NAME-role
subjects:
  - kind: ServiceAccount
    namespace: quorum
    name: $METADATA_NAME-sa

---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: $METADATA_NAME
  labels:
    app: $METADATA_NAME
  namespace: quorum
spec:
  replicas: 1
  selector:
    matchLabels:
      app: $METADATA_NAME
  serviceName: $METADATA_NAME
  volumeClaimTemplates:
    - metadata:
        name: data
      spec:
        storageClassName: nfs-client
        accessModes:
          - ReadWriteMany
        resources:
          requests:
            storage: "20Gi"
  template:
    metadata:
      labels:
        app: $METADATA_NAME
        tier: backend
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "9545"
        prometheus.io/path: "/debug/metrics/prometheus"
    spec:
      serviceAccountName: $METADATA_NAME-sa
      initContainers:
        - name: init-bootnode
          image: curlimages/curl:7.79.1
          command:
            - /bin/sh
            - -c
          args:
            - |
              exec 
              curl -X GET --connect-timeout 30 --max-time 10 --retry 6 --retry-delay 0 --retry-max-time 300 http://quorum-node-validator-1.quorum.svc.cluster.local:8545
              sleep 30
              curl -X GET --connect-timeout 30 --max-time 10 --retry 6 --retry-delay 0 --retry-max-time 300 http://quorum-node-validator-2.quorum.svc.cluster.local:8545
              sleep 30
      containers:
        - name: $METADATA_NAME
          image: quorumengineering/quorum:latest
          imagePullPolicy: IfNotPresent
          resources:
            requests:
              cpu: 100m
              memory: 1024Mi
            limits:
              cpu: 500m
              memory: 2048Mi
          env:
            - name: POD_IP
              valueFrom:
                fieldRef:
                  fieldPath: status.podIP
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: QUORUM_NETWORK_ID
              value: "1337"
            - name: QUORUM_CONSENSUS
              value: qbft
            - name: PRIVATE_CONFIG
              value: ignore
          volumeMounts:
            - name: keys
              mountPath: /config/keys/
              readOnly: true
            - name: static-nodes-file
              mountPath: /config/static-nodes
              readOnly: true
            - name: permissions-nodes-config
              mountPath: /config/permissions-nodes/
              readOnly: true
            - name: genesis-file
              mountPath: /config/quorum/
              readOnly: true
            - name: data
              mountPath: /data
          ports:
            - containerPort: 8545
              name: json-rpc
              protocol: TCP
            - containerPort: 8546
              name: ws
              protocol: TCP
            - containerPort: 8547
              name: graphql
              protocol: TCP
            - containerPort: 30303
              name: rlpx
              protocol: TCP
            - containerPort: 30303
              name: discovery
              protocol: UDP
            - containerPort: 9545
              name: metrics
              protocol: TCP
          command:
            - /bin/sh
            - -c
          args:
            - |
              exec 
              cp /config/quorum/genesis.json /data/genesis.json
              geth --datadir=/data init /data/genesis.json
              cp /config/static-nodes/static-nodes.json /data/
              cp /config/permissions-nodes/*.json /data/
              cp /config/keys/accountKeystore /data/keystore/accountKeystore
              cp /config/keys/nodekey /data/geth/nodekey
              cp /config/keys/nodekey.pub /data/geth/nodekey.pub

              geth \
              --datadir /data \
              --networkid 1337 --nodiscover --verbosity 5 \
              --permissioned \
              --syncmode full \
              --istanbul.blockperiod 1 --mine --miner.threads 1 --miner.gasprice 0 --emitcheckpoints \
              --http --http.addr 0.0.0.0 --http.port 8545 --http.corsdomain "*" --http.vhosts "*" \
              --ws --ws.addr 0.0.0.0 --ws.port 8546 --ws.origins "*" \
              --http.api admin,db,eth,debug,miner,net,shh,txpool,personal,web3,quorum,istanbul \
              --ws.api admin,db,eth,debug,miner,net,shh,txpool,personal,web3,quorum,istanbul \
              --unlock 0 --allow-insecure-unlock --password /config/keys/accountPassword \
              --metrics --pprof --pprof.addr 0.0.0.0 --pprof.port 9545 \
              --port 30303
          livenessProbe:
            httpGet:
              path: /
              port: 8545
            initialDelaySeconds: 120
            periodSeconds: 30
      volumes:
        - name: keys
          secret:
            secretName: $METADATA_NAME-keys
        - name: genesis-file
          configMap:
            name: goquorum-genesis
            items:
              - key: genesis.json
                path: genesis.json
        - name: static-nodes-file
          configMap:
            name: goquorum-peers
            items:
              - key: static-nodes.json
                path: static-nodes.json
        - name: permissions-nodes-config
          configMap:
            name: goquorum-permissioned-peers
