---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: $METADATA_NAME-storage
spec:
  storageClassName: nfs-client
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: "20Gi"
