---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "goquorum-node.fullname" . }}
  labels:
    app: {{ include "goquorum-node.fullname" . }}
  namespace: {{ .Release.Namespace }}
spec:
  type: ClusterIP
  selector:
    app: {{ include "goquorum-node.fullname" . }}
  ports:
    - name: json-rpc
      port: {{ .Values.node.goquorum.rpc.port }}
      targetPort: json-rpc
      protocol: TCP
    - name: ws
      port: {{ .Values.node.goquorum.ws.port }}
      targetPort: ws
      protocol: TCP
    - name: graphql
      port: {{ .Values.node.goquorum.graphql.port }}
      targetPort: graphql
      protocol: TCP
    - name: rlpx
      port: {{ .Values.node.goquorum.p2p.port }}
      targetPort: rlpx
      protocol: TCP
    - name: discovery
      port: {{ .Values.node.goquorum.p2p.port }}
      targetPort: discovery
      protocol: UDP
    - name: metrics
      port: {{ .Values.node.goquorum.metrics.pprofport }}
      targetPort: metrics
      protocol: TCP
